# Generated by Django 4.0.6 on 2022-07-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPostForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
    ]
